server:
  port: 9000
  tomcat:
    max-threads: 1000

spring:
  profiles:
    active: prod,multi #同时加载多个配置文件

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000 #连接等待超时时间,单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000 #一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    logSlowSql: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 1000
    pool:
      max-idle: 20 #最大空闲连接数
      min-idle: 0 #最小空闲连接数
      max-active: -1 #最大连接数，-1：没有限制
      max-wait: -1 #单位毫秒连接池最大组阻塞时间，-1：没有限制
    password:
mybatis:
  type-aliases-package: com.imooc.dataobject
  mapper-locations: classpath:mapper/*.xml
  config-location:  classpath:mybatis.xml
#logging:
  #config: classpath:logback.xml
elasticsearch:
    cluster:
        name: wali
    host: localhost
    port: 9300


#============== kafka ===================
kafka:
  consumer:
    zookeeper-connect: 112.35.79.103:2181
    bootstrap-servers: 112.35.79.103:9092
    enable-auto-commit: true
    session-timeout: 6000
    auto-commit-interval: 100
    auto-offset-reset: latest
    topic: topic1
    group-id: topic1
    concurrency: 10

  producer:
    bootstrap-servers: 112.35.79.103:9092,112.35.79.103:9093,112.35.79.103:9094
    retries: 0
    batch-size: 4096
    linger: 1
    buffer-memory: 40960

